import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiDelete, apiGet, apiGetWithQuery, apiPost, apiPut } from "../lib/api.js";
import { downloadCsv, downloadPdfTable } from "../lib/purchaseExport.js";

const tabs = ["GRN", "Stock View", "Stock Ledger", "Stock Adjustment", "Stock Transfer", "Locations"];

export default function StoreModule() {
  const qc = useQueryClient();
  const [tab, setTab] = useState("GRN");
  const [article, setArticle] = useState("");
  const [location, setLocation] = useState("");
  const [refNo, setRefNo] = useState("");
  const [adj, setAdj] = useState({ adjustmentNo: "", date: new Date().toISOString().slice(0, 10), article: "", location: "", adjustmentType: "Increase", quantity: 0, reason: "", remarks: "" });
  const [trf, setTrf] = useState({ transferNo: "", date: new Date().toISOString().slice(0, 10), article: "", fromLocation: "", toLocation: "", quantity: 0, remarks: "" });
  const [loc, setLoc] = useState({ locationCode: "", locationName: "", warehouse: "", rack: "", bin: "", status: "Active" });
  const [editLoc, setEditLoc] = useState("");

  const { data: grns } = useQuery({ queryKey: ["grn"], queryFn: () => apiGetWithQuery("/grn", { limit: 200 }), enabled: tab === "GRN" });
  const { data: balance } = useQuery({ queryKey: ["stock-balance", article, location], queryFn: () => apiGetWithQuery("/stock/balance", { article: article || undefined, location: location || undefined, limit: 500 }), enabled: tab === "Stock View" });
  const { data: ledger } = useQuery({ queryKey: ["stock-ledger", article, location, refNo], queryFn: () => apiGetWithQuery("/stock/ledger", { article: article || undefined, location: location || undefined, referenceNo: refNo || undefined, limit: 500 }), enabled: tab === "Stock Ledger" });
  const { data: locations } = useQuery({ queryKey: ["stock-locations"], queryFn: () => apiGet("/stock/locations"), enabled: tab === "Locations" });

  const createAdj = useMutation({ mutationFn: () => apiPost("/stock/adjustment", adj), onSuccess: () => qc.invalidateQueries({ queryKey: ["stock-ledger"] }) });
  const postAdj = useMutation({ mutationFn: () => apiPost(`/stock/adjustment/${adj.adjustmentNo}/post`, {}), onSuccess: () => { qc.invalidateQueries({ queryKey: ["stock-ledger"] }); qc.invalidateQueries({ queryKey: ["stock-balance"] }); } });
  const createTrf = useMutation({ mutationFn: () => apiPost("/stock/transfer", trf), onSuccess: () => qc.invalidateQueries({ queryKey: ["stock-ledger"] }) });
  const postTrf = useMutation({ mutationFn: () => apiPost(`/stock/transfer/${trf.transferNo}/post`, {}), onSuccess: () => { qc.invalidateQueries({ queryKey: ["stock-ledger"] }); qc.invalidateQueries({ queryKey: ["stock-balance"] }); } });
  const saveLoc = useMutation({ mutationFn: () => (editLoc ? apiPut(`/stock/locations/${editLoc}`, loc) : apiPost("/stock/locations", loc)), onSuccess: () => { qc.invalidateQueries({ queryKey: ["stock-locations"] }); setEditLoc(""); } });
  const deleteLoc = useMutation({ mutationFn: (code) => apiDelete(`/stock/locations/${code}`), onSuccess: () => qc.invalidateQueries({ queryKey: ["stock-locations"] }) });

  return (
    <div className="space-y-4">
      <div className="rounded-2xl border bg-white p-4"><h1 className="text-2xl font-semibold">Store</h1><p className="text-sm text-slate-600">GRN, Stock View, Stock Ledger, Adjustment, Transfer, Locations</p></div>
      <div className="flex flex-wrap gap-2 rounded-2xl border bg-white p-2">{tabs.map((x) => <button key={x} onClick={() => setTab(x)} className={tab === x ? "rounded-lg bg-slate-900 px-3 py-2 text-sm text-white" : "rounded-lg px-3 py-2 text-sm hover:bg-slate-100"}>{x}</button>)}</div>

      {tab === "GRN" ? <div className="rounded-2xl border bg-white p-4"><p className="mb-2 text-sm text-slate-600">Use API endpoints: create draft (`POST /api/grn`), post (`POST /api/grn/:grnNo/post`), cancel (`POST /api/grn/:grnNo/cancel`).</p><div className="flex flex-wrap gap-2">{(grns?.items || []).map((g) => <span key={g._id} className="rounded border px-2 py-1 text-xs">{g.grnNo} ({g.status})</span>)}</div></div> : null}

      {tab === "Stock View" ? <div className="space-y-3"><div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input className="rounded border px-3 py-2 text-sm" placeholder="Article" value={article} onChange={(e) => setArticle(e.target.value.toUpperCase())} /><input className="rounded border px-3 py-2 text-sm" placeholder="Location" value={location} onChange={(e) => setLocation(e.target.value.toUpperCase())} /><button className="rounded border px-3 py-2 text-sm" onClick={() => downloadCsv("stock-view.csv", [{ key: "article", header: "Article" }, { key: "location", header: "Location" }, { key: "onHandQty", header: "On Hand" }, { key: "availableQty", header: "Available" }], balance?.items || [])}>Export CSV</button><button className="rounded border px-3 py-2 text-sm" onClick={() => downloadPdfTable("Stock View", "", [{ key: "article", header: "Article" }, { key: "location", header: "Location" }, { key: "onHandQty", header: "On Hand" }, { key: "availableQty", header: "Available" }], balance?.items || [], "stock-view")}>Export PDF</button></div><div className="overflow-auto rounded-2xl border bg-white"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-100"><tr>{["Article", "Item Name", "Location", "On Hand", "Allocated", "RTS", "Available", "UOM"].map((h) => <th key={h} className="px-2 py-2 text-left">{h}</th>)}</tr></thead><tbody>{(balance?.items || []).map((r) => <tr key={r._id} className="border-t"><td className="px-2 py-1 font-mono">{r.article}</td><td className="px-2 py-1">{r.item?.itemName || ""}</td><td className="px-2 py-1">{r.location}</td><td className="px-2 py-1">{r.onHandQty}</td><td className="px-2 py-1">{r.allocatedQty}</td><td className="px-2 py-1">{r.rtsQty}</td><td className="px-2 py-1">{r.availableQty}</td><td className="px-2 py-1">{r.item?.uom || ""}</td></tr>)}</tbody></table></div></div> : null}

      {tab === "Stock Ledger" ? <div className="space-y-3"><div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input className="rounded border px-3 py-2 text-sm" placeholder="Article" value={article} onChange={(e) => setArticle(e.target.value.toUpperCase())} /><input className="rounded border px-3 py-2 text-sm" placeholder="Location" value={location} onChange={(e) => setLocation(e.target.value.toUpperCase())} /><input className="rounded border px-3 py-2 text-sm" placeholder="Reference No" value={refNo} onChange={(e) => setRefNo(e.target.value)} /><button className="rounded border px-3 py-2 text-sm" onClick={() => downloadCsv("stock-ledger.csv", [{ key: "transactionDate", header: "Date" }, { key: "transactionType", header: "Tx Type" }, { key: "referenceNo", header: "Reference" }, { key: "article", header: "Article" }, { key: "qtyIn", header: "In" }, { key: "qtyOut", header: "Out" }, { key: "balanceQty", header: "Balance" }], ledger?.items || [])}>Export CSV</button></div><div className="overflow-auto rounded-2xl border bg-white"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-100"><tr>{["Date", "Type", "Reference", "Article", "Item Name", "Location", "In", "Out", "Balance"].map((h) => <th key={h} className="px-2 py-2 text-left">{h}</th>)}</tr></thead><tbody>{(ledger?.items || []).map((r) => <tr key={r._id} className="border-t"><td className="px-2 py-1">{new Date(r.transactionDate).toLocaleString()}</td><td className="px-2 py-1">{r.transactionType}</td><td className="px-2 py-1">{r.referenceNo}</td><td className="px-2 py-1 font-mono">{r.article}</td><td className="px-2 py-1">{r.itemName || ""}</td><td className="px-2 py-1">{r.location}</td><td className="px-2 py-1">{r.qtyIn}</td><td className="px-2 py-1">{r.qtyOut}</td><td className="px-2 py-1">{r.balanceQty}</td></tr>)}</tbody></table></div></div> : null}

      {tab === "Stock Adjustment" ? <div className="rounded-2xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-4"><input className="rounded border px-3 py-2 text-sm" placeholder="Adjustment No" value={adj.adjustmentNo} onChange={(e) => setAdj((s) => ({ ...s, adjustmentNo: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" type="date" value={adj.date} onChange={(e) => setAdj((s) => ({ ...s, date: e.target.value }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Article" value={adj.article} onChange={(e) => setAdj((s) => ({ ...s, article: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Location" value={adj.location} onChange={(e) => setAdj((s) => ({ ...s, location: e.target.value.toUpperCase() }))} /><select className="rounded border px-3 py-2 text-sm" value={adj.adjustmentType} onChange={(e) => setAdj((s) => ({ ...s, adjustmentType: e.target.value }))}><option>Increase</option><option>Decrease</option></select><input className="rounded border px-3 py-2 text-sm" type="number" placeholder="Quantity" value={adj.quantity} onChange={(e) => setAdj((s) => ({ ...s, quantity: Number(e.target.value) }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Reason" value={adj.reason} onChange={(e) => setAdj((s) => ({ ...s, reason: e.target.value }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Remarks" value={adj.remarks} onChange={(e) => setAdj((s) => ({ ...s, remarks: e.target.value }))} /></div><div className="mt-3 flex gap-2"><button onClick={() => createAdj.mutate()} className="rounded bg-slate-900 px-3 py-2 text-sm text-white">Create Draft</button><button onClick={() => postAdj.mutate()} className="rounded border px-3 py-2 text-sm">Post</button></div></div> : null}

      {tab === "Stock Transfer" ? <div className="rounded-2xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-4"><input className="rounded border px-3 py-2 text-sm" placeholder="Transfer No" value={trf.transferNo} onChange={(e) => setTrf((s) => ({ ...s, transferNo: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" type="date" value={trf.date} onChange={(e) => setTrf((s) => ({ ...s, date: e.target.value }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Article" value={trf.article} onChange={(e) => setTrf((s) => ({ ...s, article: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="From Location" value={trf.fromLocation} onChange={(e) => setTrf((s) => ({ ...s, fromLocation: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="To Location" value={trf.toLocation} onChange={(e) => setTrf((s) => ({ ...s, toLocation: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" type="number" placeholder="Quantity" value={trf.quantity} onChange={(e) => setTrf((s) => ({ ...s, quantity: Number(e.target.value) }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Remarks" value={trf.remarks} onChange={(e) => setTrf((s) => ({ ...s, remarks: e.target.value }))} /></div><div className="mt-3 flex gap-2"><button onClick={() => createTrf.mutate()} className="rounded bg-slate-900 px-3 py-2 text-sm text-white">Create Draft</button><button onClick={() => postTrf.mutate()} className="rounded border px-3 py-2 text-sm">Post</button></div></div> : null}

      {tab === "Locations" ? <div className="space-y-3"><div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><input className="rounded border px-3 py-2 text-sm" disabled={Boolean(editLoc)} placeholder="Location Code" value={loc.locationCode} onChange={(e) => setLoc((s) => ({ ...s, locationCode: e.target.value.toUpperCase() }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Location Name" value={loc.locationName} onChange={(e) => setLoc((s) => ({ ...s, locationName: e.target.value }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Warehouse" value={loc.warehouse} onChange={(e) => setLoc((s) => ({ ...s, warehouse: e.target.value }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Rack" value={loc.rack} onChange={(e) => setLoc((s) => ({ ...s, rack: e.target.value }))} /><input className="rounded border px-3 py-2 text-sm" placeholder="Bin" value={loc.bin} onChange={(e) => setLoc((s) => ({ ...s, bin: e.target.value }))} /><select className="rounded border px-3 py-2 text-sm" value={loc.status} onChange={(e) => setLoc((s) => ({ ...s, status: e.target.value }))}><option>Active</option><option>Inactive</option></select><button onClick={() => saveLoc.mutate()} className="rounded bg-slate-900 px-3 py-2 text-sm text-white">{editLoc ? "Update" : "Create"}</button></div><div className="overflow-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-100"><tr>{["Code", "Name", "Warehouse", "Rack", "Bin", "Status", "Actions"].map((h) => <th key={h} className="px-2 py-2 text-left">{h}</th>)}</tr></thead><tbody>{(locations || []).map((r) => <tr key={r._id} className="border-t"><td className="px-2 py-1 font-mono">{r.locationCode}</td><td className="px-2 py-1">{r.locationName}</td><td className="px-2 py-1">{r.warehouse}</td><td className="px-2 py-1">{r.rack}</td><td className="px-2 py-1">{r.bin}</td><td className="px-2 py-1">{r.status}</td><td className="px-2 py-1"><button onClick={() => { setEditLoc(r.locationCode); setLoc({ locationCode: r.locationCode, locationName: r.locationName, warehouse: r.warehouse, rack: r.rack, bin: r.bin, status: r.status }); }} className="rounded border px-2 py-1 text-xs">Edit</button><button onClick={() => deleteLoc.mutate(r.locationCode)} className="ml-2 rounded border px-2 py-1 text-xs text-rose-700">Delete</button></td></tr>)}</tbody></table></div></div> : null}
    </div>
  );
}
